name: Post Competitions to Discord

on:
  schedule:
    - cron: '0 0 * * *'  # JST 9:00 に相当（GitHub ActionsはUTC）
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 pandas

      - name: Run main script
        run: python main.py

      - name: Commit and push posted.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main || true
          git add posted.json
          git commit -m "Update posted.json [skip ci]" || echo "No changes to commit"
          git push origin main || echo "Push failed (likely no new data)"
