name: Post JIA Competitions to Discord

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日午前9時（JST）に実行（GitHubはUTCなので0時）
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 pandas

      - name: Run main script
        run: python main.py

      - name: Commit and push posted.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add posted.json
          git commit -m "Update posted.json [skip ci]" || echo "No changes to commit"
          git push origin main
